### ISSUE TITLE
Reading property having multiline values

### ISSUE THREAD

**Issue by gourahari** [steveukx/properties#10]
If I have a property like following, can't be read.
```
address = {
    "line1" : "34 SE Sugarcane Avenue",
    "line2" : "Apt 101",
    "city":"Reston",
    "zipcode":12345
}
```

**Comment by steveukx** [comment]
I don't think that properties files support multi-line content, which is why this library doesn't. If you can add into the issue a reference for how a regular properties file represents multi-line content, I'll re-open this issue add it into the library for you (or please feel free to submit a pull request).

**Comment by quilicicf** [comment]
Hi, 

Resurrecting this issue because I think I understand it and can provide an example. 

```
my.multi.line.property=This is a property soooooo long that I had to \
  split into multiple lines, otherwise it would literally get unreadable.
```

The backslash-escape specifies a continuation line and is documented somewhat succinctly in [Oracle's documentation](https://docs.oracle.com/javase/6/docs/api/java/util/Properties.html) (search for `continuation line`).

Currently, the reader extracts the continued lines as keys rather than continuations of the previous value.
